server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: 中文服务
#eureka:
#  client:
#    serviceUrl:
#     defaultZone: http://127.0.0.1:8080/eureka/