server:
  port: 8081
spring:
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
  application:
    name: service
eureka:
  client:
    serviceUrl:
     defaultZone: http://erueka.talers.xyz//eureka/