server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: service
service1:
  ribbon:
    eureka:
      enabled: false
#eureka:
#  client:
#    serviceUrl:
#     defaultZone: http://127.0.0.1:8080/eureka/